apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-checker-app
  namespace: secret-checker
spec:
  schedule: "0 */3 * * *"  # Runs every 3 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: secret-checker
            azure.workload.identity/use: "true"  
        spec:
          serviceAccountName: secret-checker-sa
          containers:
          - name: secret-checker
            image: acrlibraaksdev01.azurecr.io/secret-checker:latest
            imagePullPolicy: Always
            env:
            - name: AZURE_CLIENT_ID
              value: "1a26eba2-b7a5-4c9b-9056-14668cc50e97"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          restartPolicy: OnFailure
